Slightly different implementation

diff --git a/docs/wsl-ssh-agent-relay b/docs/wsl-ssh-agent-relay
--- a/docs/wsl-ssh-agent-relay
+++ b/docs/wsl-ssh-agent-relay
@@ -55,9 +55,7 @@ usage() {
     log ""
     log "    -v|--verbose       verbose mode"
     log ""
-    log "    -c|--no-com-test   Continue running regardless failed communication test."
-    log "                       Use with start and foreground commands when ssh agent"
-    log "                       is not running or ready yet."
+    log "    -s|--skip-test     skip ssh-agent communication test"
     log ""
     log "  COMMAND: start, stop, foreground"
 }
@@ -77,7 +75,7 @@ main() {
 
     POSITIONAL=()
     VERBOSE=""
-    NO_COM_TEST=""
+    SKIP_SSH_TEST=""
     while (($# > 0)); do
         case "$1" in
         -v | --verbose)
@@ -85,8 +83,8 @@ main() {
             shift # shift once since flags have no values
             ;;
 
-        -c | --no-com-test)
-            NO_COM_TEST="TRUE"
+        -s | --skip-test)
+            SKIP_SSH_TEST="TRUE"
             shift
             ;;
 
@@ -168,21 +166,13 @@ relay() {
     fi
     log "Relay is running with PID: ${SOCAT_WSL_AGENT_SSH_PID}"
 
-    log -n "Polling remote ssh-agent..."
-    SSH_AUTH_SOCK="${WSL_AGENT_SSH_SOCK}" ssh-add -L >/dev/null 2>&1
-    status=$?
-    if [[ "$status" != 0 ]]; then
-        log "[$status] Failure communicating with ssh-agent"
-        if [[ -n "$NO_COM_TEST" ]]; then
-            log "Continuing despite the failed communication test."
-        else
-            die
-        fi
-    else
+    if [[ -z "$SKIP_SSH_TEST" ]]; then
+        log -n "Polling remote ssh-agent..."
+        SSH_AUTH_SOCK="${WSL_AGENT_SSH_SOCK}" ssh-add -L >/dev/null 2>&1 || die "[$?] Failure communicating with ssh-agent"
         log "OK"
     fi
 
-    # Everything checks, we are ready for actions
+    # Everything necessary checks, we are ready for actions
     log "Entering wait..."
     wait ${SOCAT_WSL_AGENT_SSH_PID}
 }
